# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='password',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
