# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20180514_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
